export const environment = {
  production: false,
  STREAMING_URL: 'https://dev-portal.securedatacommons.com/guacamole/?authToken=',
  REGION: 'us-east-1',
  USER_POOL_ID: 'us-east-1_RqSIpOZN3',
  CLIENT_ID: '53smb4abi8ovad66j1r4o5u2pd',
  IDENTITY_PROVIDER: 'dev-dot-ad',
  APP_DOMAIN: 'dev-sdc-dot-webportal',
  REDIRECT_URL: 'https://dev-portal.securedatacommons.com/index.html',
  API_ENDPOINT: 'https://dev-portal.securedatacommons.com/webportal-api/',
  LOGIN_GOV_COGNITO_APP_CLIENT_ID: '1nej89a7dlvd3f0dt5ocsmrgli',
  ACCOUNT_LINK_URL: 'https://dev-portal.securedatacommons.com/account-link-dev',
  LINK_ACCOUNT_PATH: 'dev-link-account-private',
  ACCOUNT_LINKED_PATH: 'dev-account-linked-private',
  RESET_TEMPORARY_PASSWORD_PATH: 'dev-reset-temporary-password-private',
};
