AUTHORIZERID = "0gd98s"
COGNITO_USER_POOL = "dev-sdc-dot-cognito-pool"
USER_POOL_ID = "us-east-1_sNIwupW53"
RECEIVER_EMAIL = "sdc-support@dot.gov"
RESTAPIID = "po6lv3qcoh"
TABLENAME_AUTOEXPORT_USERS = "dev-AutoExportUsersTable"
TABLENAME_AVAILABLE_DATASET = "dev-AvailableDataset"
TABLENAME_EXPORT_FILE_REQUEST = "dev-RequestExportTable"
TABLENAME_MANAGE_DISK = "dev-ManageDiskspaceRequestsTable"
TABLENAME_MANAGE_DISK_INDEX = "dev-diskspace-username-index"
TABLENAME_MANAGE_UPTIME = "dev-ScheduleUptimeTable"
TABLENAME_MANAGE_UPTIME_INDEX = "dev-scheduleuptime-username-index"
TABLENAME_MANAGE_USER = "dev-ManageUserWorkstationTable"
TABLENAME_MANAGE_USER_INDEX = "dev-workstation-username-index"
TABLENAME_TRUSTED_USERS = "dev-TrustedUsersTable"
TABLENAME_USER_STACKS = "dev-UserStacksTable"

